blank_issues_enabled: false
contact_links:
  - name: General Questions (Discussions)
    url: https://github.com/madiver/dextraderpro-alpha/discussions
    about: Ask questions and share non-trackable discussion topics.
